### ISSUE TITLE
Images showing

### ISSUE THREAD

**Issue by adjebbar** [AbhinashShrestha/airbnb-clone#1]
Hey.

I followed your method described in the readme, but when I deploy the site it doesn't sow images as in the demo??

Thanks.

**Comment by AbhinashShrestha** [comment]
Hey! Thanks for reaching out.
Have you uploaded any image to your cloudinary account?
Please refer to the following youtube video for troubleshooting: https://www.youtube.com/watch?v=c_-b_isI4vg.

**Comment by AbhinashShrestha** [comment]
Hey! Thanks for reaching out.
Have you uploaded any image to your cloudinary account?
Please refer to the following youtube video for troubleshooting: https://www.youtube.com/watch?v=c_-b_isI4vg.
